### PR TITLE
Binary-reversal

### PR DESCRIPTION
**Pull request by omudavid**
i seem to be well to do with when i input the numbers in my code from the test file and run it. but the npm test is bringing up a strange figure. please help.

### CODE REVIEW

**Comment by tracie96** [comment]
did you "npm install"?

**Comment by tracie96** [comment]
did you push list sorting test, because your code is running that test on binary sorting code.

**Comment by tracie96** [comment]
you have to provide the list sorting challenge for the test to run on it.

**Comment by dexkode4** [comment]
> i seem to be well to do with when i input the numbers in my code from the test file and run it. but the npm test is bringing up a strange figure. please help.

you can't convert a string literal to binary with toString()....you gotta convert "value" to integer first

**Comment by omudavid** [comment]
@dexkode4 what do you think of my sorting code

**Comment by dexkode4** [comment]
> @dexkode4 what do you think of my sorting code

it's awesome .... although I think the time complexity could go from O(n^2) to O(n)

**Pull request merged**
